# oh-my-zsh extra settings for plugins

# oh-my-zsh configuration generated by NixOS
plugins=(vi-mode)

ZSH_THEME="af-magic"
source ~/.oh-my-zsh/oh-my-zsh.sh






# History options should be set in .zshrc and after oh-my-zsh sourcing.
HISTSIZE="10000"
SAVEHIST="10000"

HISTFILE="$HOME/.zsh_history"
mkdir -p "$(dirname "$HISTFILE")"

setopt HIST_FCNTL_LOCK
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE
unsetopt HIST_EXPIRE_DUPS_FIRST
setopt SHARE_HISTORY
setopt EXTENDED_HISTORY

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
